name: Document with Slither

on:
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  document:
    name: Document with Slither
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'generate-docs')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Document with Slither
        uses: crytic/slither-docs-action@main
        with:
          target: project
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}